version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_adonis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: talent  
      MYSQL_DATABASE: app         
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_adonis
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: talent  
    ports:
      - "8080:80"
    depends_on:
      - mysql

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: gateways_mock
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"

  app:
    build: .
    container_name: adonis_app
    restart: always
    ports:
      - "3333:3333"
    environment:
      DB_CONNECTION: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: talent
      MYSQL_DB_NAME: app
    depends_on:
      - mysql
      - gateways-mock
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    command: ["node", "build/bin/server.js"]

volumes:
  mysql_data: