version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_adonis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: talent  
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # Verifica se o MySQL está pronto
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_adonis
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: talent
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: gateways_mock
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"

  app:
    build: .
    container_name: adonis_app
    restart: always
    ports:
      - "3333:3333"
    environment:
      HOST: 0.0.0.0  
      PORT: 3333
      NODE_ENV: development
      DB_CONNECTION: mysql
      DB_HOST: mysql  
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: talent
      DB_DATABASE: app
    # volumes:
    #   - ./:/app  
    #   - /app/node_modules  
    command: ["node", "build/bin/server.js"]  
    depends_on:
      - mysql
      - gateways-mock

volumes:
  mysql_data: